name: Deploy devnet.blog
on:
  push:
    branches:
      - main
    paths:
      - content/**


jobs:
  build_job:
    name: Deploy blog
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Checkout master branch
        id: checkout-master
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pelican-4.2.0-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pelican-4.2.0-
      - name: Install Pelican
        run: |
          pip install -r requirements.txt
      - name: Generate site
        id: run-pelican
        run: |
          pelican content --output output --settings publishconf.py
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: deploy
          publish_dir: ./output
          user_name: 'deploy-bot'
          user_email: 'deploy-bot@noreply.github.io'
      - name: Notice
        run: |
          echo '::notice:: Site deployed.'

